---
- name: Install and configure Suricata with EveBox
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
      tags: update

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - software-properties-common
        - jq
        - wget
        - gnupg
        - apt-transport-https
        - unzip
        - libpcre2-dev
        - libyaml-dev
        - libjansson-dev
        - libpcap-dev
        - gawk
        - libunwind-dev
        - libmagic-dev
        - liblz4-dev
        - libcap-ng-dev
      tags: install_packages

    - name: Add EveBox GPG key
      apt_key:
        url: https://evebox.org/files/GPG-KEY-evebox
        state: present
      tags: add_evebox_gpg_key

    - name: Add EveBox repository
      apt_repository:
        repo: deb http://evebox.org/files/debian stable main
        state: present
      tags: add_evebox_repo

    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
      args:
        executable: /bin/bash
        creates: ~/.cargo
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.cargo/bin"
      tags: install_rust

    - name: Set Rust environment
      shell: source "{{ ansible_env.HOME }}/.cargo/env"
      args: 
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.cargo/bin"
      tags: install_rust
    
    - name: Set default Rust toolchain
      shell: rustup default stable
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.cargo/bin"
      tags: set_default_rust_toolchain

    - name: Update Rust
      shell: rustup update
      environment:
        PATH: "{{ ansible_env.PATH }}:~/.cargo/bin"
      tags: update_rust

    - name: Download Suricata source
      get_url:
        url: https://www.openinfosecfoundation.org/download/suricata-7.0.1.tar.gz
        dest: /tmp/suricata-7.0.1.tar.gz
      tags: download_suricata_source

    - name: Extract Suricata source
      unarchive:
        src: /tmp/suricata-7.0.1.tar.gz
        dest: /tmp
        remote_src: yes
      tags: extract_suricata_source

    - name: Compile and install Suricata
      command: >
        ./configure && make && make install
      args:
        chdir: /tmp/suricata-7.0.1
      tags: compile_install_suricata

    - name: Install EveBox
      apt:
        name: evebox
        state: present
      tags: install_evebox

    - name: Run ldconfig
      command: ldconfig
      tags: run_ldconfig

    - name: Update Suricata rules
      shell: suricata-update update-sources
      tags: update_suricata_rules

    - name: Enable Suricata rules
      shell: suricata-update enable-source et/open
      tags: enable_suricata_rules

    - name: Apply Suricata updates
      shell: suricata-update
      tags: apply_suricata_updates

    - name: List enabled Suricata rules sources
      shell: suricata-update list-sources --enabled
      tags: list_enabled_suricata_rules_sources

    - name: Download Suricata configuration
      get_url:
        url: https://github.com/xslizik/csc-debi-suri/raw/main/wget/suricata.yaml
        dest: /usr/local/var/lib/suricata/suricata.yaml
      tags: download_suricata_config

    - name: Download classification.config
      get_url:
        url: https://github.com/xslizik/csc-debi-suri/raw/main/wget/classification.config
        dest: /usr/local/var/lib/suricata/classification.config
      tags: download_classification_config

    - name: Download reference.config
      get_url:
        url: https://github.com/xslizik/csc-debi-suri/raw/main/wget/reference.config
        dest: /usr/local/var/lib/suricata/reference.config
      tags: download_reference_config

    - name: Download evebox_pcap.sh
      get_url:
        url: https://github.com/xslizik/csc-debi-suri/raw/main/evebox_pcap.sh
        dest: /usr/local/bin/evebox_pcap.sh
        mode: '0755'
      tags: download_evebox_pcap_script

    - name: Download pcaps
      get_url:
        url: https://github.com/pan-unit42/Wireshark-quizzes/raw/main/2023-01-Unit42-Wireshark-quiz.pcap.zip
        dest: /tmp/2023-01-Unit42-Wireshark-quiz.pcap.zip
      tags: download_pcaps

    - name: Extract pcaps
      unarchive:
        src: /tmp/2023-01-Unit42-Wireshark-quiz.pcap.zip
        dest: /tmp
        remote_src: yes
        extra_opts: --password=infected
      tags: extract_pcaps

    - name: Remove downloaded pcaps zip file
      file:
        path: /tmp/2023-01-Unit42-Wireshark-quiz.pcap.zip
        state: absent
      tags: remove_pcaps_zip
