# Generated by Cyber Sandbox Creator 3.1.0
# https://gitlab.ics.muni.cz/muni-kypo-csc/cyber-sandbox-creator
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

ansible_groups = {
  "hosts" => ["home"], 
  "routers" => [], 
  "ssh" => ["home"], 
  "winrm" => [], 
  "ansible" => ["home"]
}

Vagrant.configure("2") do |config|
  # Device(host): home
  config.vm.boot_timeout = 300000000
  config.vm.define "home" do |device|
    device.vm.hostname = "home"
    device.vm.box = "munikypo/debian-10"
    device.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    device.vm.synced_folder ".",
      "/vagrant",
      type: "rsync",
      rsync__exclude: ".git/"
    device.vm.network "private_network",
      virtualbox__intnet: "network",
      ip: "10.10.30.5",
      netmask: "255.255.255.0"
    device.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "preconfig/playbook.yml"
      ansible.groups = ansible_groups
      ansible.limit = "home"
    end
    device.vm.provision "ansible_local" do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.groups = ansible_groups
      ansible.limit = "home"
    end
  end
end
