- name: Copy Excercises
  copy:
    src: transfer/excercises
    dest: /home/vagrant/

- name: Run dynamic_flags.py
  command:
    cmd:  "python /home/vagrant/excercises/dynamic_flags.py {{ first_flag }} {{ second_flag }}"
    chdir: /home/vagrant/excercises/

- name: Remove dynamic_flags.py 
  ansible.builtin.file:
    path: /home/vagrant/excercises/dynamic_flags.py
    state: absent