- name: Create /usr/local/lib/lua directory
  ansible.builtin.file:
    path: /usr/local/lib/lua
    state: directory
    mode: '0755'

- name: Create /usr/local/lib/lua/5.2 directory
  ansible.builtin.file:
    path: /usr/local/lib/lua/5.2
    state: directory
    mode: '0755'

- name: Copy files to home
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'transfer/requests/templates', dest: '/root' }
    - { src: 'transfer/requests/protect_flags.py', dest: '/root/protect_flags.py' }
    - { src: 'transfer/requests/replace.sh', dest: '/root/replace.sh' }
    - { src: 'transfer/requests/protect_flags.service', dest: '/etc/systemd/system/protect_flags.service' }
    - { src: 'transfer/wireshark/ja3.lua', dest: '/usr/lib/x86_64-linux-gnu/wireshark/plugins/ja3.lua'}
    - { src: 'transfer/wireshark/md5.lua', dest: '/usr/local/lib/lua/5.2/md5.lua'}

- name: Add dynamic flag protect_flags.py
  command: "bash /root/replace.sh /root/protect_flags.py {{ third_flag }} {{ fourth_flag }} {{ fifth_flag }}"

- name: Reload system daemon
  command: "systemctl daemon-reload"

- name: Enable protect_flags service
  command: "systemctl enable protect_flags.service"

- name: Start protect_flags service
  command: "systemctl start protect_flags.service"