---
- name: Configrue ssh tunel from Kali to Suri
  hosts: kali
  become: yes
  tasks:
    - name: Create directory /home/kali/.ssh and set owner and group
      file:
        path: /home/kali/.ssh
        state: directory
        owner: kali
        group: kali
        mode: '0775'
        recurse: yes

    - name: Copy private SSH key
      copy:
        src: ./ssh/suri
        dest: /home/kali/.ssh/
      become_user: kali

    - name: Copy public SSH key
      copy:
        src: ./ssh/suri.pub
        dest: /home/kali/.ssh/
      become_user: kali

- name: Main playbook to install and configure DVWA and Suricata with EveBox
  hosts: debi-suri
  become: yes
  tasks:
    - name: Read public SSH key
      slurp:
        path: ./ssh/suri.pub
      register: local_file_content

    - name: Enable SSH from Kali to Suri
      lineinfile:
        path: /home/vagrant/.ssh/authorized_keys
        line: "{{ local_file_content['content'] | b64decode }}"
        insertafter: EOF

    - name: Install packages
      include_tasks: ./suri/0_suri_packages.yml

    - name: Set up DVWA docker
      include_tasks: ./suri/1_dvwa_docker.yml

    - name: Add Suricata
      include_tasks: ./suri/2_suri_download.yml

    - name: Add EveBox
      include_tasks: ./suri/3_evebox_download.yml

    - name: Set proper Suricata permissions
      include_tasks: ./suri/4_suri_groups.yml

    - name: Add Suricata excercises
      include_tasks: ./suri/5_suri_excercises.yml
    