---
- name: Install and configure DVWA, Suricata, EveBox
  hosts: debi-suri
  become: yes
  vars_files:
    - ./suri/suri_vars
  tasks:
    - name: Install packages
      include_tasks: ./suri/0_suri_packages.yml

    - name: Add Suricata
      include_tasks: ./suri/1_suri_download.yml

    - name: Set proper Suricata permissions
      include_tasks: ./suri/2_suri_groups.yml

    - name: Set up DVWA docker
      include_tasks: ./suri/3_dvwa_docker.yml

    - name: Add EveBox
      include_tasks: ./suri/4_evebox_download.yml

    - name: Add Suricata excercises
      include_tasks: ./suri/5_suri_excercises.yml
    
- name: Set up malicious DVWA requests script
  hosts: kali
  become: yes
  vars_files:
    - ./kali/kali_vars
  tasks:
    - name: Set up user accounts
      include_tasks: ./kali/0_kali_users.yml
    
    - name: Prepare environment
      include_tasks: ./kali/1_malicious_requests.yml